### ISSUE TITLE
DnD Campaign Removal

### ISSUE THREAD

**Issue by CallumWigg** [OwenFeik/owen-bot#4]
Campaign's cannot be removed, as doing so removes the current campaign, and a new campaign cannot be selected if there is no current campaign.
Should instead check if there are other campaigns, and if so, automatically select the previously selected campaign, or just select the first one in the series.

**Comment by OwenFeik** [comment]
Resolved; issue was caused by "campaign" being placed after the "require campaign" check; therefore it couldn't be used without an active campaign.
